# -*- coding: utf-8 -*-

from models.mysql.system import t_operation, SystemEngine


# 菜单操作
# 添加菜单
OPERATION_MENU_ADD = 'OPERATION_MENU_ADD'
# 修改菜单
OPERATION_MENU_EDIT = 'OPERATION_MENU_EDIT'
# 删除菜单
OPERATION_MENU_DEL = 'OPERATION_MENU_DEL'
# 禁用菜单
OPERATION_MENU_DISABLE = 'OPERATION_MENU_DISABLE'
# 启用菜单
OPERATION_MENU_ENABLE = 'OPERATION_MENU_ENABLE'

# 权限功能操作
# 查看权限
OPERATION_PERMISSION_VIEW = 'OPERATION_PERMISSION_VIEW'
# 添加权限
OPERATION_PERMISSION_ADD = 'OPERATION_PERMISSION_ADD'
# 修改权限
OPERATION_PERMISSION_EDIT = 'OPERATION_PERMISSION_EDIT'
# 删除权限
OPERATION_PERMISSION_DEL = 'OPERATION_PERMISSION_DEL'
# 禁用权限
OPERATION_PERMISSION_DISABLE = 'OPERATION_PERMISSION_DISABLE'
# 启用权限
OPERATION_PERMISSION_ENABLE = 'OPERATION_PERMISSION_ENABLE'

# 用户功能操作
# 查看用户
OPERATION_USER_VIEW = 'OPERATION_USER_VIEW'
# 添加用户
OPERATION_USER_ADD = 'OPERATION_USER_ADD'
# 修改用户
OPERATION_USER_EDIT = 'OPERATION_USER_EDIT'
# 删除用户
OPERATION_USER_DEL = 'OPERATION_USER_DEL'
# 禁用用户
OPERATION_USER_DISABLE = 'OPERATION_USER_DISABLE'
# 启用用户
OPERATION_USER_ENABLE = 'OPERATION_USER_ENABLE'

# 用户组功能操作
# 查看用户组
OPERATION_GROUP_VIEW = 'OPERATION_GROUP_VIEW'
# 添加用户组
OPERATION_GROUP_ADD = 'OPERATION_GROUP_ADD'
# 修改用户组
OPERATION_GROUP_EDIT = 'OPERATION_GROUP_EDIT'
# 删除用户组
OPERATION_GROUP_DEL = 'OPERATION_GROUP_DEL'
# 禁用用户组
OPERATION_GROUP_DISABLE = 'OPERATION_GROUP_DISABLE'
# 启用用户组
OPERATION_GROUP_ENABLE = 'OPERATION_GROUP_ENABLE'

# 角色功能操作
# 查看角色
OPERATION_ROLE_VIEW = 'OPERATION_ROLE_VIEW'
# 添加角色
OPERATION_ROLE_ADD = 'OPERATION_ROLE_ADD'
# 修改角色
OPERATION_ROLE_EDIT = 'OPERATION_ROLE_EDIT'
# 删除角色
OPERATION_ROLE_DEL = 'OPERATION_ROLE_DEL'
# 禁用角色
OPERATION_ROLE_DISABLE = 'OPERATION_ROLE_DISABLE'
# 启用角色
OPERATION_ROLE_ENABLE = 'OPERATION_ROLE_ENABLE'

# 给用户分配用户组的操作
OPERATION_USER_GROUP_BIND = 'OPERATION_USER_GROUP_BIND'

# 给用户分配角色的操作
OPERATION_USER_ROLE_BIND = 'OPERATION_USER_ROLE_BIND'

# 给用户组分配角色的操作
OPERATION_ROLE_GROUP_BIND = 'OPERATION_ROLE_GROUP_BIND'

# 给角色分配权限的操作
OPERATION_ROLE_PERMISSION_BIND = 'OPERATION_ROLE_PERMISSION_BIND'

# 通用配置操作
# 查看配置
OPERATION_CONFIG_VIEW = 'OPERATION_CONFIG_VIEW'
# 添加配置
OPERATION_CONFIG_ADD = 'OPERATION_CONFIG_ADD'
# 修改配置
OPERATION_CONFIG_EDIT = 'OPERATION_CONFIG_EDIT'
# 删除配置
OPERATION_CONFIG_DEL = 'OPERATION_CONFIG_DEL'
# 禁用配置
OPERATION_CONFIG_DISABLE = 'OPERATION_CONFIG_DISABLE'
# 启用配置
OPERATION_CONFIG_ENABLE = 'OPERATION_CONFIG_ENABLE'


class TableOperation(SystemEngine):
    table = t_operation
